<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Seguridad de cuenta | APM</title><?php require ROOT.'/shared/head_assets.php'; ?>
<style>.security-grid{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(280px,.8fr);gap:22px}.security-status{display:flex;align-items:center;gap:16px;padding:18px;border-radius:16px;background:<?= $status['enabled']?'#ecfdf5':'#fff7ed' ?>;border:1px solid <?= $status['enabled']?'#a7f3d0':'#fed7aa' ?>}.security-icon{width:54px;height:54px;border-radius:15px;display:grid;place-items:center;background:#fff;color:<?= $status['enabled']?'#059669':'#d97706' ?>;font-size:1.5rem}.security-form{display:grid;gap:14px}.security-form input{width:100%;padding:12px 13px;border:1px solid var(--line);border-radius:10px;font:inherit}.secret-box{padding:15px;border:1px dashed var(--teal-500);background:#f0fdff;border-radius:12px;word-break:break-all;font-family:monospace;font-size:1rem;letter-spacing:.08em}.security-note{padding:13px 15px;border-radius:12px;background:#eff6ff;color:#1e4f72;font-size:.84rem;line-height:1.55}@media(max-width:850px){.security-grid{grid-template-columns:1fr}}</style></head><body>
<div id="overlay" class="overlay" onclick="closeSidebar()"></div><button class="sidebar-open-btn" id="sidebarOpenBtn" onclick="openSidebar()" aria-label="Abrir menú"><i class="bi bi-layout-sidebar"></i></button><div class="app"><?php require ROOT.'/shared/menu.php'; ?><section class="content"><?php $topbarSubtitle='Seguridad de cuenta';$topbarShowSearch=false;require ROOT.'/shared/topbar.php'; ?><main class="main"><div class="content-shell">
<section class="hero"><div><div class="hero-kicker">Cuenta · Protección de acceso</div><h2>Seguridad de la cuenta</h2><p>Administre la autenticación en dos pasos y proteja su acceso institucional.</p></div></section>
<?php if($mensaje): ?><div class="security-status" style="margin-bottom:18px;background:#ecfdf5;border-color:#a7f3d0"><i class="bi bi-check-circle-fill" style="color:#059669"></i><?= htmlspecialchars($mensaje) ?></div><?php endif; ?><?php if($error): ?><div class="security-status" style="margin-bottom:18px;background:#fff1f2;border-color:#fecdd3"><i class="bi bi-exclamation-triangle-fill" style="color:#dc2626"></i><?= htmlspecialchars($error) ?></div><?php endif; ?>
<div class="security-grid"><section class="card" style="padding:24px"><div class="security-status"><div class="security-icon"><i class="bi <?= $status['enabled']?'bi-shield-check':'bi-shield-exclamation' ?>"></i></div><div><h3 style="margin:0 0 4px">Doble autenticación <?= $status['enabled']?'activa':'inactiva' ?></h3><p style="margin:0;color:var(--ink-600);font-size:.85rem"><?= $status['enabled']?'Su cuenta requiere contraseña y código TOTP.':'Active un segundo factor para reducir el riesgo de accesos no autorizados.' ?></p></div></div>
<?php if(!$status['enabled'] && !$enrollment): ?><form method="post" action="<?= BASE_URL ?>/cuenta/seguridad/preparar-mfa" style="margin-top:20px"><input type="hidden" name="_csrf" value="<?= htmlspecialchars(Auth::csrfToken()) ?>"><button class="btn btn-primary" type="submit"><i class="bi bi-phone"></i> Configurar aplicación autenticadora</button></form><?php endif; ?>
<?php if(!$status['enabled'] && $enrollment): ?><div style="margin-top:20px"><h3>1. Agregue la cuenta</h3><p style="color:var(--ink-600);font-size:.86rem">En Microsoft Authenticator, Google Authenticator o Authy seleccione “Ingresar clave de configuración”.</p><div class="secret-box" id="mfaSecret"><?= htmlspecialchars($enrollment['secret']) ?></div><details style="margin-top:10px"><summary>Mostrar URI técnica</summary><div class="secret-box" style="margin-top:8px;font-size:.72rem;letter-spacing:0"><?= htmlspecialchars($enrollment['uri'] ?? '') ?></div></details><h3>2. Confirme el código</h3><form class="security-form" method="post" action="<?= BASE_URL ?>/cuenta/seguridad/activar-mfa"><input type="hidden" name="_csrf" value="<?= htmlspecialchars(Auth::csrfToken()) ?>"><input name="codigo" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="Código de 6 dígitos" required><button class="btn btn-primary" type="submit">Activar doble autenticación</button></form></div><?php endif; ?>
<?php if($status['enabled']): ?><form class="security-form" method="post" action="<?= BASE_URL ?>/cuenta/seguridad/desactivar-mfa" style="margin-top:22px" onsubmit="return handleDesactivarMfaSubmit(event)"><input type="hidden" name="_csrf" value="<?= htmlspecialchars(Auth::csrfToken()) ?>"><h3>Desactivar protección</h3><input type="password" name="clave" autocomplete="current-password" placeholder="Contraseña actual" required><input name="codigo" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="Código actual" required><button class="btn btn-outline" type="submit">Desactivar segundo factor</button></form><script>
// Hash SHA-256 de la clave ANTES de enviarla (ver js/password-hash.js) --
// se hace después del confirm() nativo, no antes, para no calcular el hash
// de una acción que el usuario todavía puede cancelar.
function handleDesactivarMfaSubmit(e) {
    if (!confirm('¿Desactivar la doble autenticación de su cuenta?')) return false;
    if (!window.hashPasswordFieldsBeforeSubmit) return true;
    e.preventDefault();
    hashPasswordFieldsBeforeSubmit(e.target, ['clave']).then(function () { e.target.submit(); });
    return false;
}
</script><?php endif; ?></section>
<aside class="card" style="padding:24px"><h3><i class="bi bi-info-circle"></i> Recomendaciones</h3><div class="security-note">Use una aplicación autenticadora institucional. No tome capturas ni comparta la clave secreta. Si pierde el dispositivo, solicite a un administrador el restablecimiento del segundo factor.</div><a class="btn btn-outline" style="margin-top:16px" href="<?= BASE_URL ?>/cuenta/cambiar-clave"><i class="bi bi-key"></i> Cambiar contraseña</a></aside></div>
</div></main></section></div><?php require ROOT.'/shared/footer_scripts.php'; ?></body></html>
