<?php
$o=$origen??[];$docs=$documentos??[];
$h=static fn($v):string=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$etiquetas=['FICHA_PERSONAL'=>'Formulario principal','ACCION_PERSONAL'=>'Acción de Personal','ESTUDIO_SOCIOECONOMICO'=>'Estudio socioeconómico','PAZ_SALVO'=>'Paz y Salvo'];
$tipo=(string)($o['tipo_documento']??'');$actual=null;foreach($docs as $d)if(($d['estado']??'')==='FIRMADO'){$actual=$d;break;}
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Documento firmado | Portal Portuario APM</title><?php require ROOT.'/shared/head_assets.php'; ?>
<style>
.signed-shell{display:grid;gap:20px}.signed-hero,.signed-card{background:var(--surface,#fff);border:1px solid var(--line,#dbe5ef);border-radius:20px;box-shadow:var(--shadow-md,0 12px 28px rgba(15,50,70,.08))}.signed-hero{padding:24px 28px;display:flex;align-items:center;justify-content:space-between;gap:20px;flex-wrap:wrap}.signed-kicker{font-size:.72rem;font-weight:800;letter-spacing:.18em;color:var(--ocean-700,#087c9a);text-transform:uppercase}.signed-hero h1{margin:6px 0;font-size:1.65rem}.signed-hero p{margin:0;color:var(--ink-600,#64748b)}.signed-status{display:inline-flex;align-items:center;gap:7px;border-radius:999px;padding:8px 13px;font-weight:800;font-size:.78rem;background:#dcfce7;color:#047857}.signed-status.pending{background:#fff7db;color:#9a5b00}.signed-card{padding:24px}.signed-grid{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(280px,.8fr);gap:22px}.upload-box{border:1px dashed #7cc9da;background:#f4fcfe;border-radius:16px;padding:22px}.upload-box input[type=file]{display:block;width:100%;margin:13px 0;padding:12px;border:1px solid var(--line);border-radius:12px;background:#fff}.source-data{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.source-data div{background:#f7fafc;border:1px solid var(--line);border-radius:12px;padding:12px}.source-data small{display:block;text-transform:uppercase;letter-spacing:.09em;color:var(--ink-600);font-size:.67rem}.source-data strong{display:block;margin-top:5px}.signed-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.signed-table{width:100%;border-collapse:collapse}.signed-table th,.signed-table td{padding:12px;border-bottom:1px solid var(--line);text-align:left;vertical-align:middle}.signed-table th{font-size:.7rem;text-transform:uppercase;letter-spacing:.12em;color:var(--ink-600)}.hash{font-family:ui-monospace,Consolas,monospace;font-size:.7rem;word-break:break-all}.version-state{display:inline-flex;padding:5px 10px;border-radius:999px;background:#dcfce7;color:#047857;font-size:.7rem;font-weight:800}.version-state.old{background:#eef2f6;color:#64748b}@media(max-width:850px){.signed-grid{grid-template-columns:1fr}.source-data{grid-template-columns:1fr}.signed-card{overflow:auto}}
</style></head><body><div id="overlay" class="overlay" onclick="closeSidebar()"></div><button class="sidebar-open-btn" id="sidebarOpenBtn" onclick="openSidebar()" aria-label="Abrir menú"><i class="bi bi-layout-sidebar"></i></button>
<div class="app"><?php require ROOT.'/shared/menu.php'; ?><section class="content"><?php $topbarShowSearch=true;$topbarBackUrl=BASE_URL.'/talento-humano/reporte?empleado_id='.(int)$o['empleado_id'];$topbarBackLabel='Volver al historial';require ROOT.'/shared/topbar.php'; ?><main class="main"><div class="content-shell signed-shell">
<section class="signed-hero"><div><div class="signed-kicker">Expediente documental firmado</div><h1><?= $h($etiquetas[$tipo]??'Formulario institucional') ?></h1><p><?= $h($o['numero_documento']??'') ?> · <?= $h(trim(($o['apellidos']??'').' '.($o['nombres']??''))) ?></p></div><span class="signed-status <?= $actual?'':'pending' ?>"><i class="bi bi-<?= $actual?'patch-check-fill':'hourglass-split' ?>"></i><?= $actual?'Completo y firmado':'Pendiente de documento firmado' ?></span></section>
<?php if(!empty($_GET['msg'])): ?><div class="alert <?= ($_GET['ok']??'0')==='1'?'alert-success':'alert-error' ?>"><?= $h($_GET['msg']) ?></div><?php endif; ?>
<section class="signed-card signed-grid"><div><h2 style="margin-top:0">Incorporar formulario legalizado</h2><p>Imprima el formato autorizado, complete las firmas, escanéelo íntegramente en un solo PDF y súbalo aquí. El formato generado por el sistema no será modificado.</p><?php if(!empty($o['legalizable'])): ?><form method="post" enctype="multipart/form-data" action="<?= BASE_URL ?>/talento-humano/documentos-firmados/subir"><input type="hidden" name="_csrf" value="<?= $h(Auth::csrfToken()) ?>"><input type="hidden" name="tipo" value="<?= $h($tipo) ?>"><input type="hidden" name="origen_id" value="<?= (int)$o['origen_id'] ?>"><div class="upload-box"><label for="signedPdf"><strong>PDF completo, escaneado y firmado *</strong></label><input id="signedPdf" type="file" name="documento_firmado" accept="application/pdf,.pdf" required><small>Máximo 20 MB. No se aceptan archivos protegidos con contraseña.</small><label for="signedNotes" style="display:block;margin-top:15px"><strong>Observaciones</strong></label><textarea id="signedNotes" name="observaciones" rows="3" maxlength="500" placeholder="Firmas presentes, número de trámite u observación documental"></textarea><div class="signed-actions"><button class="btn btn-primary" type="submit"><i class="bi bi-cloud-arrow-up"></i> Subir documento firmado</button></div></div></form><?php else: ?><div class="alert alert-warning"><i class="bi bi-shield-exclamation"></i> Complete la aprobación o el cierre del formulario antes de cargar su versión firmada.</div><?php endif; ?></div><aside><h3 style="margin-top:0">Documento de origen</h3><div class="source-data"><div><small>Funcionario</small><strong><?= $h(trim(($o['apellidos']??'').' '.($o['nombres']??''))) ?></strong></div><div><small>Identificación</small><strong><?= $h($o['identificacion']??'') ?></strong></div><div><small>Número</small><strong><?= $h($o['numero_documento']??'') ?></strong></div><div><small>Estado del registro</small><strong><?= $h($o['estado']??'') ?></strong></div></div><div class="signed-actions"><a class="btn btn-outline" target="_blank" href="<?= BASE_URL.'/'.$h($o['imprimir_url']??'') ?>"><i class="bi bi-printer"></i> Imprimir formato</a><a class="btn btn-ghost" href="<?= BASE_URL ?>/talento-humano/reporte?empleado_id=<?= (int)$o['empleado_id'] ?>"><i class="bi bi-clock-history"></i> Ver historial</a></div></aside></section>
<section class="signed-card"><h2 style="margin-top:0">Versiones conservadas</h2><div style="overflow:auto"><table id="documentosFirmadosTable" class="signed-table" data-apm-datatable data-dt-page-length="10" data-dt-order='[[0,"desc"]]' data-dt-order-disabled="3,5" data-dt-search-placeholder="Buscar versión, archivo o usuario…" data-dt-empty="Aún no se ha cargado el documento firmado."><thead><tr><th>Versión</th><th>Archivo</th><th>Fecha y usuario</th><th>Integridad</th><th>Estado</th><th>Acción</th></tr></thead><tbody><?php if(!$docs): ?><tr data-dt-empty><td colspan="6" style="text-align:center;padding:28px">Aún no se ha cargado el documento firmado.</td></tr><?php endif; ?><?php foreach($docs as $d): ?><tr><td data-order="<?= (int)$d['version_documento'] ?>"><strong>v<?= (int)$d['version_documento'] ?></strong></td><td><?= $h($d['nombre_original']) ?><small style="display:block"><?= number_format(((int)$d['tamano_bytes'])/1048576,2) ?> MB</small></td><td data-order="<?= $h($d['fecha_carga']) ?>"><?= $h(date('d/m/Y H:i',strtotime((string)$d['fecha_carga']))) ?><small style="display:block"><?= $h($d['usuario_carga']) ?></small></td><td><span class="hash" title="SHA-256"><?= $h(substr((string)$d['sha256'],0,16)) ?>…</span></td><td><span class="version-state <?= $d['estado']==='FIRMADO'?'':'old' ?>"><?= $h($d['estado']) ?></span></td><td><a class="btn btn-outline" target="_blank" href="<?= BASE_URL ?>/talento-humano/documentos-firmados/descargar?id=<?= (int)$d['documento_id'] ?>"><i class="bi bi-file-earmark-pdf"></i> Abrir</a></td></tr><?php endforeach; ?></tbody></table></div></section>
</div></main></section></div><?php require ROOT.'/shared/footer_scripts.php'; ?></body></html>
