<!doctype html>
<html lang="es">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Movimiento grupal | APM</title><?php require ROOT.'/shared/head_assets.php'; ?></head>
<body><div class="app"><?php require ROOT.'/shared/menu.php'; ?><section class="content">
<?php $topbarTitle='Movimiento interno grupal';$topbarSubtitle='Sin Acción de Personal';$topbarShowSearch=false;$topbarBackUrl=BASE_URL.'/talento-humano/directorio?modo=movimiento';$topbarBackLabel='Volver';require ROOT.'/shared/topbar.php'; ?>
<main class="main"><div class="content-shell"><section class="card"><div class="card-header"><div><h3>Mover <?= count($seleccion) ?> servidores en una sola operación</h3><p>El lote es atómico: si un registro no cumple las reglas, ningún empleado será movido.</p></div></div>
<form class="batch-grid" method="post" action="<?= BASE_URL ?>/talento-humano/empleado/mover-lote" data-draft-context="movimiento-grupal:<?= hash('sha256', implode(',', array_map(static fn($e)=>(int)$e['empleado_id'],$seleccion))) ?>" onsubmit="return confirm('¿Confirma el movimiento grupal de <?= count($seleccion) ?> empleados? Cada funcionario conservará su cargo actual.')"><input type="hidden" name="_csrf" value="<?= htmlspecialchars(Auth::csrfToken()) ?>">
<div class="batch-list"><table><thead><tr><th>Cédula</th><th>Funcionario</th><th>Área actual</th><th>Cargo actual</th></tr></thead><tbody><?php foreach($seleccion as $e): ?><tr><td><?= htmlspecialchars($e['cedula']??'') ?><input type="hidden" name="empleados[]" value="<?= (int)$e['empleado_id'] ?>"></td><td><?= htmlspecialchars(trim(($e['apellidos']??'').' '.($e['nombres']??''))) ?></td><td><?= htmlspecialchars($e['direccion_area']??'') ?></td><td><?= htmlspecialchars($e['cargo']??'') ?></td></tr><?php endforeach; ?></tbody></table></div>
<div class="batch-field"><label for="fecha_movimiento">Fecha efectiva</label><input id="fecha_movimiento" name="fecha_movimiento" type="date" value="<?= date('Y-m-d') ?>" required></div>
<div></div>
<div class="batch-field"><label for="unidad_destino_id">Área / Dirección de destino</label><select id="unidad_destino_id" name="unidad_destino_id" required><option value="">Seleccione...</option><?php foreach($areas as $a): ?><option value="<?= (int)$a['unidad_id'] ?>"><?= htmlspecialchars(($a['unidad_padre_id']?'↳ ':'').$a['nombre_unidad']) ?></option><?php endforeach; ?></select></div>
<div class="batch-field"><label>Cargos vigentes</label><div class="movement-current"><i class="bi bi-lock-fill"></i> Cada funcionario conservará el cargo mostrado en la tabla.</div></div>
<div class="batch-field" style="grid-column:1/-1"><label for="motivo">Motivo común del movimiento</label><textarea id="motivo" name="motivo" rows="4" maxlength="500" required></textarea></div>
<div class="batch-actions"><a class="btn btn-outline" href="<?= BASE_URL ?>/talento-humano/directorio">Cancelar</a><button class="btn btn-primary" type="submit"><i class="bi bi-people-fill"></i> Aplicar movimiento grupal</button></div>
</form></section></div></main></section></div><?php require ROOT.'/shared/footer_scripts.php'; ?></body></html>
