<?php
$h=static fn($v)=>htmlspecialchars((string)($v??''),ENT_QUOTES,'UTF-8');
$secciones=[
 'JEFE_INMEDIATO'=>['Jefe inmediato',['informe_gestion'=>'Informe de gestión/trabajo entregado','documentos_entregados'=>'Documentos, archivos e información entregados','receptor_nombre'=>'Nombre de quien recibe','receptor_cargo'=>'Cargo de quien recibe','fecha_entrega'=>'Fecha de entrega']],
 'TALENTO_HUMANO'=>['Talento Humano',['credencial_entregada'=>'Credencial institucional entregada','declaracion_bienes'=>'Declaración jurada de bienes presentada','vacaciones_no_gozadas'=>'Vacaciones no gozadas / observación']],
 'FINANCIERO'=>['Dirección Financiera',['anticipo_sueldo'=>'Saldo de anticipo de sueldo','valor_saldo'=>'Valor ($)','otros_saldos'=>'Otros saldos u obligaciones']],
 'ADMINISTRATIVO'=>['Dirección Administrativa',['acta_bienes'=>'Acta de entrega de bienes y custodios']],
 'TIC'=>['Tecnologías de la Información',['correo_deshabilitado'=>'Correo institucional deshabilitado','quipux_deshabilitado'=>'Usuario Quipux deshabilitado']]
];
?><!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $documento?'Gestionar':'Nuevo' ?> Paz y Salvo | APM</title><?php require ROOT.'/shared/head_assets.php'; ?><style>
.ps-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.ps-form label{display:block;font-size:.82rem;font-weight:700;color:var(--ink-600);margin-bottom:5px}.ps-form input,.ps-form select,.ps-form textarea{width:100%;padding:11px 12px;border:1px solid var(--line);border-radius:10px;background:#fff}.ps-section{margin-top:16px;border:1px solid var(--line);border-radius:14px;overflow:hidden}.ps-section summary{padding:15px 18px;background:#f2f8fb;font-weight:800;color:var(--navy-900);cursor:pointer;display:flex;justify-content:space-between}.ps-section form{padding:18px}.ps-section .ps-grid{margin-bottom:12px}.ps-badge{padding:4px 9px;border-radius:999px;background:#fff;border:1px solid var(--line);font-size:.72rem}.ps-readonly{background:#f5f7fa!important}.yesno{display:grid;grid-template-columns:1fr 1fr;gap:8px}.yesno select{width:100%}@media(max-width:850px){.ps-grid{grid-template-columns:1fr}}
</style></head><body><div class="app"><?php require ROOT.'/shared/menu.php'; ?><section class="content"><?php $topbarSubtitle=$documento?'Gestión de certificaciones':'Nuevo documento de salida';$topbarBackHref=BASE_URL.'/talento-humano/paz-salvo';$topbarBackLabel='Volver';require ROOT.'/shared/topbar.php'; ?><main class="main"><div class="content-shell">
<?php if(isset($_GET['msg'])): ?><div class="alert <?= ($_GET['ok']??'0')==='1'?'alert-success':'alert-error' ?>"><?= $h($_GET['msg']) ?></div><?php endif; ?>
<section class="hero"><div><div class="hero-kicker">Paz y Salvo institucional</div><h2><?= $documento?$h($documento['numero_documento']):'Crear documento' ?></h2><p><?= $documento?'Complete cada certificación. El documento solo podrá cerrarse cuando las cinco áreas estén conformes.':'Seleccione una Acción de Personal de salida aprobada; los datos del funcionario se completan automáticamente.' ?></p></div><?php if($documento): ?><div class="hero-actions"><a class="btn btn-primary" target="_blank" href="<?= BASE_URL ?>/talento-humano/paz-salvo/imprimir?id=<?= (int)$documento['paz_salvo_id'] ?>"><i class="bi bi-file-pdf"></i> Ver PDF</a></div><?php endif; ?></section>
<?php if(!$documento): ?><section class="card ps-form" style="padding:22px"><form method="post" action="<?= BASE_URL ?>/talento-humano/paz-salvo/guardar"><input type="hidden" name="_csrf" value="<?= $h(Auth::csrfToken()) ?>"><input type="hidden" id="empleado_id" name="empleado_id"><div class="ps-grid"><div><label>Acción de salida aprobada *</label><select id="accion_salida_id" name="accion_salida_id" required><option value="">Seleccione...</option><?php foreach($acciones as $a): ?><option value="<?= (int)$a['accion_id'] ?>" data-empleado="<?= (int)$a['empleado_id'] ?>" data-salida="<?= $h($a['fecha_rige_desde']) ?>"><?= $h($a['numero_accion'].' · '.$a['identificacion'].' · '.$a['apellidos'].' '.$a['nombres']) ?></option><?php endforeach; ?></select></div><div><label>Lugar</label><input name="lugar" value="Manta" required></div><div><label>Fecha de emisión *</label><input type="date" name="fecha_emision" value="<?= InstitutionalClock::today()->format('Y-m-d') ?>" required></div><div><label>Fecha de salida *</label><input id="fecha_salida" type="date" name="fecha_salida" required></div></div><div style="margin-top:14px"><label>Observaciones generales</label><textarea name="observaciones_generales" rows="3"></textarea></div><div style="display:flex;justify-content:flex-end;margin-top:16px"><button class="btn btn-primary"><i class="bi bi-floppy"></i> Crear documento</button></div></form></section><script>document.getElementById('accion_salida_id').addEventListener('change',function(){const o=this.options[this.selectedIndex];document.getElementById('empleado_id').value=o.dataset.empleado||'';document.getElementById('fecha_salida').value=o.dataset.salida||'';});</script>
<?php else: ?><section class="card ps-form" style="padding:22px"><div class="ps-grid"><div><label>Funcionario</label><input class="ps-readonly" readonly value="<?= $h($documento['apellidos'].' '.$documento['nombres']) ?>"></div><div><label>Cédula</label><input class="ps-readonly" readonly value="<?= $h($documento['identificacion']) ?>"></div><div><label>Cargo / Área</label><input class="ps-readonly" readonly value="<?= $h(($documento['cargo']??'').' · '.($documento['area']??'')) ?>"></div><div><label>Vínculo / Acción</label><input class="ps-readonly" readonly value="<?= $h(($documento['tipo_contrato']??'').' · '.$documento['numero_accion']) ?>"></div><div><label>Ingreso</label><input class="ps-readonly" readonly value="<?= $h($documento['fecha_ingreso']) ?>"></div><div><label>Salida</label><input class="ps-readonly" readonly value="<?= $h($documento['fecha_salida']) ?>"></div></div></section>
<?php foreach($secciones as $codigo=>[$titulo,$campos]): $s=$documento['secciones'][$codigo]??['estado'=>'PENDIENTE','datos'=>[]]; ?><details class="ps-section" <?= $s['estado']!=='PENDIENTE'?'':'open' ?>><summary><span><i class="bi bi-patch-check"></i> <?= $h($titulo) ?></span><span class="ps-badge"><?= $h($s['estado']) ?></span></summary><form class="ps-form" method="post" action="<?= BASE_URL ?>/talento-humano/paz-salvo/guardar-seccion"><input type="hidden" name="_csrf" value="<?= $h(Auth::csrfToken()) ?>"><input type="hidden" name="paz_salvo_id" value="<?= (int)$documento['paz_salvo_id'] ?>"><input type="hidden" name="codigo_seccion" value="<?= $h($codigo) ?>"><div class="ps-grid"><?php foreach($campos as $nombre=>$etiqueta): ?><div><label><?= $h($etiqueta) ?></label><?php if(str_contains($nombre,'entregad')||str_contains($nombre,'presentada')||str_contains($nombre,'deshabilitado')): ?><select name="datos[<?= $h($nombre) ?>]"><option value="">Seleccione</option><option value="SI" <?= ($s['datos'][$nombre]??'')==='SI'?'selected':'' ?>>Sí</option><option value="NO" <?= ($s['datos'][$nombre]??'')==='NO'?'selected':'' ?>>No</option><option value="NO APLICA" <?= ($s['datos'][$nombre]??'')==='NO APLICA'?'selected':'' ?>>No aplica</option></select><?php else: ?><input <?= str_contains($nombre,'fecha')?'type="date"':'' ?> name="datos[<?= $h($nombre) ?>]" value="<?= $h($s['datos'][$nombre]??'') ?>"><?php endif; ?></div><?php endforeach; ?><div><label>Responsable</label><input name="responsable_nombre" value="<?= $h($s['responsable_nombre']??'') ?>"></div><div><label>Puesto</label><input name="responsable_puesto" value="<?= $h($s['responsable_puesto']??'') ?>"></div><div><label>Sumilla</label><input name="sumilla" value="<?= $h($s['sumilla']??'') ?>"></div><div><label>Resultado *</label><select name="estado" required><?php foreach(['PENDIENTE','CONFORME','OBSERVADO'] as $e): ?><option <?= ($s['estado']??'')===$e?'selected':'' ?>><?= $e ?></option><?php endforeach; ?></select></div></div><div><label>Observaciones</label><textarea name="observaciones" rows="3"><?= $h($s['observaciones']??'') ?></textarea></div><div style="display:flex;justify-content:flex-end;margin-top:12px"><button class="btn btn-primary"><i class="bi bi-floppy"></i> Guardar <?= $h($titulo) ?></button></div></form></details><?php endforeach; ?>
<?php if($documento['estado']==='COMPLETO'): ?><form method="post" action="<?= BASE_URL ?>/talento-humano/paz-salvo/cerrar" style="display:flex;justify-content:flex-end;margin-top:18px"><input type="hidden" name="_csrf" value="<?= $h(Auth::csrfToken()) ?>"><input type="hidden" name="id" value="<?= (int)$documento['paz_salvo_id'] ?>"><button class="btn btn-primary"><i class="bi bi-lock"></i> Cerrar documento definitivo</button></form><?php endif; ?>
<?php endif; ?></div></main></section></div><?php require ROOT.'/shared/footer_scripts.php'; ?></body></html>
