<?php
$totalRegistros = count($datosReporte);
$columnas = $reporteActivo['columns'];
$totales = [];
foreach ($columnas as $clave => $columna) {
    if (in_array($columna['type'] ?? '', ['money','number'], true)) {
        $totales[$clave] = array_sum(array_map(function ($fila) use ($clave) { return (float)($fila[$clave] ?? 0); }, $datosReporte));
    }
}
$parametrosSalida = array_merge(['route'=>'reportes','tab'=>$tabActivo], $filtros);
$parametrosSalida = array_filter($parametrosSalida, function ($valor) { return $valor !== ''; });
$urlExportar = 'index.php?' . http_build_query(array_merge($parametrosSalida, ['action'=>'exportar']));
$urlImprimir = 'index.php?' . http_build_query(array_merge($parametrosSalida, ['action'=>'imprimir']));
$claveValorResumen = $reporteActivo['summary_money'] ?? '';
$valorResumen = $claveValorResumen !== '' ? (float)($totales[$claveValorResumen] ?? 0) : 0.0;
?>

<style>
.reports-hero{display:flex;justify-content:space-between;align-items:center;gap:18px;margin-bottom:18px;padding:23px;border:1px solid rgba(37,99,235,.15);border-radius:20px;background:linear-gradient(135deg,rgba(37,99,235,.09),rgba(14,165,233,.025))}.reports-hero h1{margin:0 0 6px;font-size:27px}.reports-hero p{margin:0;color:var(--text-muted);line-height:1.5}.reports-hero-icon{width:55px;height:55px;display:grid;place-items:center;flex:0 0 auto;border-radius:16px;background:#2563eb;color:#fff;font-size:23px;box-shadow:0 10px 22px rgba(37,99,235,.22)}
.report-tabs{display:grid;grid-template-columns:repeat(5,minmax(145px,1fr));gap:9px;margin-bottom:18px}.report-tab{display:flex;align-items:center;gap:10px;min-width:0;padding:12px;border:1px solid var(--border-color);border-radius:13px;background:var(--panel-bg);color:var(--text-color);text-decoration:none;transition:.18s}.report-tab:hover{border-color:#93c5fd;transform:translateY(-1px)}.report-tab.active{border-color:#2563eb;background:#eff6ff;color:#1d4ed8;box-shadow:0 8px 18px rgba(37,99,235,.1)}.report-tab i{width:31px;height:31px;display:grid;place-items:center;flex:0 0 auto;border-radius:9px;background:var(--secondary-bg);color:#64748b}.report-tab.active i{background:#dbeafe;color:#2563eb}.report-tab span{overflow:hidden;font-size:11px;font-weight:800;text-overflow:ellipsis;white-space:nowrap}
.report-filter-panel{padding:20px;margin-bottom:18px;border:1px solid rgba(148,163,184,.22);border-radius:18px;background:var(--panel-bg);box-shadow:0 10px 28px rgba(15,23,42,.045)}.filter-intro{display:flex;justify-content:space-between;align-items:start;gap:16px;margin-bottom:17px}.filter-intro h2{margin:0 0 4px;font-size:17px}.filter-intro p{margin:0;color:var(--text-muted);font-size:11px}.active-report-badge{padding:7px 10px;border-radius:999px;background:#eff6ff;color:#1d4ed8;font-size:10px;font-weight:800}.report-filters{display:grid;grid-template-columns:repeat(12,1fr);gap:12px;align-items:end}.report-filter{grid-column:span 2;min-width:0}.report-filter.wide{grid-column:span 4}.report-filter label{display:block;margin-bottom:6px;color:var(--text-muted);font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.04em}.report-filter input,.report-filter select{width:100%;height:41px;padding:0 11px;border:1px solid var(--border-color);border-radius:10px;background:var(--panel-bg);color:var(--text-color);box-sizing:border-box}.report-filter input:focus,.report-filter select:focus{outline:none;border-color:#60a5fa;box-shadow:0 0 0 3px rgba(37,99,235,.1)}.filter-buttons{grid-column:span 2;display:flex;gap:8px}.filter-buttons a,.filter-buttons button{height:41px;display:inline-flex;align-items:center;justify-content:center;gap:7px;text-decoration:none}.filter-buttons button{flex:1;border:0;cursor:pointer}
.report-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:18px}.summary-card{padding:16px;border:1px solid rgba(148,163,184,.2);border-radius:15px;background:var(--panel-bg)}.summary-card span,.summary-card strong{display:block}.summary-card span{color:var(--text-muted);font-size:10px;text-transform:uppercase;font-weight:800}.summary-card strong{margin-top:7px;font-size:23px;letter-spacing:-.025em}.summary-card.primary strong{color:#2563eb}.summary-card.money strong{color:#059669}
.results-panel{overflow:hidden;border:1px solid rgba(148,163,184,.22);border-radius:18px;background:var(--panel-bg);box-shadow:0 12px 30px rgba(15,23,42,.05)}.results-header{display:flex;justify-content:space-between;align-items:center;gap:15px;padding:17px 20px;border-bottom:1px solid var(--border-color);background:var(--secondary-bg)}.results-header h3{margin:0 0 3px;font-size:15px}.results-header p{margin:0;color:var(--text-muted);font-size:10px}.result-actions{display:flex;gap:8px;flex-wrap:wrap}.result-actions a{display:inline-flex;align-items:center;gap:7px;text-decoration:none}.report-table-wrap{overflow:auto;max-height:620px}.report-table{width:100%;border-collapse:collapse;white-space:nowrap}.report-table th{position:sticky;top:0;z-index:1;padding:11px 12px;background:#f8fafc;color:#64748b;font-size:9px;text-transform:uppercase;letter-spacing:.04em;text-align:left;border-bottom:1px solid var(--border-color)}.report-table td{max-width:300px;padding:11px 12px;border-bottom:1px solid rgba(148,163,184,.15);font-size:11px;overflow:hidden;text-overflow:ellipsis}.report-table tbody tr:hover{background:#f8fbff}.report-table td.money{text-align:right;color:#047857;font-weight:700}.report-table td.number{text-align:right;font-weight:700}.report-table td.code{color:#2563eb;font-family:ui-monospace,monospace;font-weight:700}.report-table td.status span{display:inline-flex;padding:5px 8px;border-radius:999px;background:#ecfdf5;color:#047857;font-size:9px;font-weight:800}.report-table tfoot td{position:sticky;bottom:0;background:#f8fafc;font-weight:800}.report-empty{padding:60px 25px;text-align:center;color:var(--text-muted)}.report-empty i{display:block;margin-bottom:13px;font-size:38px;color:#93c5fd}.report-empty strong{display:block;margin-bottom:5px;color:var(--text-color)}.report-error{margin-bottom:18px;padding:14px;border:1px solid #fecaca;border-radius:12px;background:#fef2f2;color:#b91c1c}.report-pagination{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:13px 18px;border-top:1px solid var(--border-color);font-size:11px}.pagination-buttons{display:flex;gap:6px}.pagination-buttons button{padding:6px 10px;border:1px solid var(--border-color);border-radius:8px;background:var(--panel-bg);cursor:pointer}.pagination-buttons button:disabled{opacity:.4;cursor:not-allowed}
@media(max-width:1100px){.report-tabs{grid-template-columns:repeat(3,1fr)}.report-filter{grid-column:span 3}.report-filter.wide{grid-column:span 6}.filter-buttons{grid-column:span 3}}@media(max-width:720px){.reports-hero{align-items:flex-start}.report-tabs{grid-template-columns:1fr 1fr}.report-filters{grid-template-columns:1fr}.report-filter,.report-filter.wide,.filter-buttons{grid-column:auto}.report-summary{grid-template-columns:1fr 1fr}.results-header{align-items:flex-start;flex-direction:column}}
.report-table td.price{text-align:right;color:#047857;font-weight:700}
</style>

<header class="reports-hero animate-fade-in"><div><h1>Centro de reportes</h1><p>Información consolidada de todas las funciones del sistema, con filtros combinables y resultados exportables.</p></div><div class="reports-hero-icon"><i class="fa-solid fa-file-lines"></i></div></header>

<nav class="report-tabs animate-fade-in" aria-label="Tipos de reporte"><?php foreach ($catalogoReportes as $clave => $reporte): ?><a class="report-tab <?= $clave === $tabActivo ? 'active' : '' ?>" href="index.php?route=reportes&amp;tab=<?= urlencode($clave) ?>"><i class="fa-solid <?= htmlspecialchars($reporte['icon']) ?>"></i><span><?= htmlspecialchars($reporte['label']) ?></span></a><?php endforeach; ?></nav>

<section class="report-filter-panel animate-fade-in">
    <div class="filter-intro"><div><h2><?= htmlspecialchars($reporteActivo['label']) ?></h2><p><?= htmlspecialchars($reporteActivo['description']) ?></p></div><span class="active-report-badge"><i class="fa-solid <?= htmlspecialchars($reporteActivo['icon']) ?>"></i> Reporte activo</span></div>
    <form class="report-filters" action="index.php" method="get">
        <input type="hidden" name="route" value="reportes"><input type="hidden" name="tab" value="<?= htmlspecialchars($tabActivo) ?>"><input type="hidden" name="generar" value="1">
        <?php if (!empty($reporteActivo['date_expr'])): ?><div class="report-filter"><label>Fecha desde</label><input type="date" name="fecha_inicio" value="<?= htmlspecialchars($filtros['fecha_inicio']) ?>"></div><div class="report-filter"><label>Fecha hasta</label><input type="date" name="fecha_fin" value="<?= htmlspecialchars($filtros['fecha_fin']) ?>"></div><?php endif; ?>
        <div class="report-filter"><label>ID exacto</label><input type="number" min="1" name="id_exacto" value="<?= htmlspecialchars($filtros['id_exacto']) ?>" placeholder="Ej. 125"></div>
        <div class="report-filter"><label>ID desde</label><input type="number" min="1" name="id_inicio" value="<?= htmlspecialchars($filtros['id_inicio']) ?>"></div>
        <div class="report-filter"><label>ID hasta</label><input type="number" min="1" name="id_fin" value="<?= htmlspecialchars($filtros['id_fin']) ?>"></div>
        <?php if (!empty($reporteActivo['status_expr'])): ?><div class="report-filter"><label>Estado / tipo</label><input list="estados-reporte" name="estado" value="<?= htmlspecialchars($filtros['estado']) ?>" placeholder="Todos"><datalist id="estados-reporte"><?php foreach (($reporteActivo['statuses'] ?? []) as $valor): ?><option value="<?= htmlspecialchars($valor) ?>"><?php endforeach; ?></datalist></div><?php endif; ?>
        <?php if (!empty($reporteActivo['provider_expr'])): ?><div class="report-filter"><label>Proveedor</label><input list="proveedores-reporte" name="proveedor" value="<?= htmlspecialchars($filtros['proveedor']) ?>" placeholder="Todos"><datalist id="proveedores-reporte"><?php foreach ($proveedores as $valor): ?><option value="<?= htmlspecialchars($valor) ?>"><?php endforeach; ?></datalist></div><?php endif; ?>
        <?php if (!empty($reporteActivo['category_expr']) || !empty($reporteActivo['category_condition'])): ?><div class="report-filter"><label>Categoría</label><select name="categoria"><option value="">Todas</option><?php foreach ($categorias as $categoria): ?><option value="<?= (int)$categoria['id'] ?>" <?= (string)$categoria['id'] === $filtros['categoria'] ? 'selected' : '' ?>><?= htmlspecialchars(($categoria['codigo'] ?? '').' · '.$categoria['nombre']) ?></option><?php endforeach; ?></select></div><?php endif; ?>
        <?php if (!empty($reporteActivo['stock_filter'])): ?><div class="report-filter"><label>Disponibilidad</label><select name="stock"><option value="">Todos</option><option value="sin_stock" <?= $filtros['stock']==='sin_stock'?'selected':'' ?>>Sin existencia</option><option value="stock_bajo" <?= $filtros['stock']==='stock_bajo'?'selected':'' ?>>Stock bajo</option><option value="sin_responsable" <?= $filtros['stock']==='sin_responsable'?'selected':'' ?>>Sin responsable</option></select></div><?php endif; ?>
        <div class="report-filter wide"><label>Búsqueda general</label><input type="search" name="termino" value="<?= htmlspecialchars($filtros['termino']) ?>" placeholder="Código, nombre, documento, usuario, descripción..."></div>
        <div class="filter-buttons"><a class="btn-outline" href="index.php?route=reportes&amp;tab=<?= urlencode($tabActivo) ?>" title="Limpiar filtros"><i class="fa-solid fa-eraser"></i></a><button class="btn-primary" type="submit"><i class="fa-solid fa-filter"></i> Generar</button></div>
    </form>
</section>

<?php if ($errorReporte): ?><div class="report-error"><i class="fa-solid fa-triangle-exclamation"></i> <?= htmlspecialchars($errorReporte) ?></div><?php endif; ?>

<?php if ($generarReporte): ?>
<section class="report-summary animate-fade-in">
    <div class="summary-card primary"><span>Registros encontrados</span><strong><?= number_format($totalRegistros) ?></strong></div>
    <div class="summary-card"><span>Filtros activos</span><strong><?= count(array_filter($filtros, function($v){return $v!=='';})) ?></strong></div>
    <div class="summary-card money"><span>Valor consolidado</span><strong><?= htmlspecialchars(CommonHelper::formatearImporte($valorResumen)) ?></strong></div>
    <div class="summary-card"><span>Generado</span><strong style="font-size:16px"><?= date('d/m/Y H:i') ?></strong></div>
</section>

<section class="results-panel animate-fade-in">
    <header class="results-header"><div><h3>Resultados · <?= htmlspecialchars($reporteActivo['label']) ?></h3><p>La exportación incluye todos los registros filtrados, no solo la página visible.</p></div><div class="result-actions"><a class="btn-outline" href="<?= htmlspecialchars($urlExportar) ?>"><i class="fa-solid fa-file-excel"></i> Excel / CSV</a><a class="btn-primary" target="_blank" href="<?= htmlspecialchars($urlImprimir) ?>"><i class="fa-solid fa-print"></i> Imprimir / PDF</a></div></header>
    <?php if (!$datosReporte): ?><div class="report-empty"><i class="fa-solid fa-folder-open"></i><strong>No se encontraron registros</strong><span>Ajuste uno o varios filtros e inténtelo nuevamente.</span></div><?php else: ?>
    <div class="report-table-wrap"><table class="report-table" id="tabla-reporte"><thead><tr><?php foreach ($columnas as $columna): ?><th><?= htmlspecialchars($columna['label']) ?></th><?php endforeach; ?></tr></thead><tbody><?php foreach ($datosReporte as $indice => $fila): ?><tr data-report-row="<?= $indice ?>"><?php foreach ($columnas as $clave => $columna): $tipo=$columna['type']??''; $valor=$fila[$clave]??''; ?><td class="<?= htmlspecialchars($tipo) ?>" title="<?= htmlspecialchars((string)$valor) ?>"><?php if ($tipo==='price'): ?><?= htmlspecialchars(CommonHelper::formatearPrecio($valor)) ?><?php elseif ($tipo==='money'): ?><?= htmlspecialchars(CommonHelper::formatearImporte($valor)) ?><?php elseif ($tipo==='number'): ?><?= number_format((float)$valor,2) ?><?php elseif ($tipo==='date' && $valor): ?><?= htmlspecialchars(date('d/m/Y H:i',strtotime((string)$valor))) ?><?php elseif ($tipo==='status'): ?><span><?= htmlspecialchars((string)$valor) ?></span><?php else: ?><?= htmlspecialchars((string)$valor) ?><?php endif; ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody><tfoot><tr><?php foreach ($columnas as $clave => $columna): $tipo=$columna['type']??''; ?><td class="<?= htmlspecialchars($tipo) ?>"><?php if (isset($totales[$clave])): ?><?= $tipo==='money' ? htmlspecialchars(CommonHelper::formatearImporte($totales[$clave])) : number_format($totales[$clave],2) ?><?php endif; ?></td><?php endforeach; ?></tr></tfoot></table></div>
    <div class="report-pagination"><span id="report-page-info"></span><div class="pagination-buttons"><button type="button" id="report-prev"><i class="fa-solid fa-angle-left"></i> Anterior</button><button type="button" id="report-next">Siguiente <i class="fa-solid fa-angle-right"></i></button></div></div>
    <?php endif; ?>
</section>
<?php else: ?><div class="report-empty animate-fade-in"><i class="fa-solid fa-sliders"></i><strong>Seleccione los criterios del reporte</strong><span>Puede combinar fecha, ID, estado, proveedor, categoría y búsqueda general.</span></div><?php endif; ?>

<?php if ($generarReporte && $datosReporte): ?><script>
(function(){var rows=[].slice.call(document.querySelectorAll('[data-report-row]')),page=1,size=50,total=Math.ceil(rows.length/size),info=document.getElementById('report-page-info'),prev=document.getElementById('report-prev'),next=document.getElementById('report-next');function render(){var start=(page-1)*size,end=Math.min(start+size,rows.length);rows.forEach(function(row,i){row.style.display=i>=start&&i<end?'':'none';});info.textContent='Mostrando '+(start+1)+' a '+end+' de '+rows.length+' registros';prev.disabled=page<=1;next.disabled=page>=total;}prev.addEventListener('click',function(){if(page>1){page--;render();}});next.addEventListener('click',function(){if(page<total){page++;render();}});render();})();
</script><?php endif; ?>
