[PHP]
engine = On
short_open_tag = Off
precision = 14
output_buffering = 4096
zlib.output_compression = Off
implicit_flush = Off
serialize_precision = -1
zend.enable_gc = On
expose_php = Off

max_execution_time = 120
max_input_time = 120
memory_limit = 256M
max_input_vars = 3000

error_reporting = E_ALL
display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = "C:\inetpub\logs\PortalPortuario\php-error.log"

post_max_size = 25M
upload_max_filesize = 20M
max_file_uploads = 20
file_uploads = On

default_mimetype = "text/html"
default_charset = "UTF-8"
date.timezone = "America/Guayaquil"

extension_dir = "C:\php85-nts\ext"
extension = curl
extension = fileinfo
extension = gd
extension = mbstring
extension = openssl
extension = php_sqlsrv_85_nts_x64.dll
extension = php_pdo_sqlsrv_85_nts_x64.dll

opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 10000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2

cgi.force_redirect = 0
cgi.fix_pathinfo = 1
fastcgi.impersonate = 1
fastcgi.logging = 0

session.use_strict_mode = 1
session.use_only_cookies = 1
session.cookie_httponly = 1
session.cookie_secure = 1
session.cookie_samesite = "Strict"
