<?php
$totalActivos = max(0, (int)($stats['total'] ?? 0));
$totalConsumo = max(0, (int)($stats['totalConsumoCorriente'] ?? 0));
$totalFijo = max(0, (int)($stats['totalActivoFijo'] ?? 0));
$valorInventariado = max(0.0, (float)($stats['valorInventariado'] ?? 0));
$porcentajeConsumo = $totalActivos > 0 ? ($totalConsumo / $totalActivos) * 100 : 0;
$porcentajeFijo = $totalActivos > 0 ? ($totalFijo / $totalActivos) * 100 : 0;
$valorPromedio = $totalActivos > 0 ? $valorInventariado / $totalActivos : 0;
$operativo = is_array($resumenOperativo ?? null) ? $resumenOperativo : [];
$movimientos = is_array($operativo['movimientos'] ?? null) ? $operativo['movimientos'] : [];
?>

<style>
.dashboard-hero{display:flex;justify-content:space-between;align-items:center;gap:20px;padding:24px;margin-bottom:20px;border:1px solid rgba(37,99,235,.16);border-radius:20px;background:linear-gradient(135deg,rgba(37,99,235,.09),rgba(14,165,233,.025));box-shadow:0 12px 32px rgba(15,23,42,.055)}
.dashboard-hero h1{margin:0 0 7px;font-size:28px;letter-spacing:-.03em}.dashboard-hero p{margin:0;color:var(--text-muted);line-height:1.5}.dashboard-actions{display:flex;gap:10px;flex-wrap:wrap}.dashboard-actions a{display:inline-flex;align-items:center;gap:8px;text-decoration:none;white-space:nowrap}
.dashboard-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px;margin-bottom:18px}.dashboard-kpis .stat-card{position:relative;min-width:0;overflow:hidden;border:1px solid rgba(148,163,184,.22);border-radius:18px;box-shadow:0 10px 28px rgba(15,23,42,.055)}.dashboard-kpis .stat-card:after{content:'';position:absolute;inset:auto 0 0;height:4px;background:var(--accent,#2563eb)}.dashboard-kpis .stat-card:nth-child(2){--accent:#0ea5e9}.dashboard-kpis .stat-card:nth-child(3){--accent:#10b981}.dashboard-kpis .stat-card:nth-child(4){--accent:#f59e0b}.dashboard-kpis .stat-value{font-size:clamp(22px,2vw,33px);line-height:1.05;letter-spacing:-.035em}
.dashboard-grid{display:grid;grid-template-columns:1.15fr .85fr .9fr;gap:16px;margin-bottom:20px}.dashboard-card{padding:20px;border:1px solid rgba(148,163,184,.22);border-radius:18px;background:var(--panel-bg);box-shadow:0 10px 28px rgba(15,23,42,.045)}.card-heading{display:flex;justify-content:space-between;gap:12px;margin-bottom:15px}.card-heading h3{margin:0 0 4px;font-size:15px}.card-heading p{margin:0;color:var(--text-muted);font-size:11px}
.priority-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.priority-card{display:grid;grid-template-columns:34px 1fr auto;align-items:center;gap:9px;min-height:64px;padding:10px;border:1px solid var(--priority-border,#dbeafe);border-radius:12px;background:var(--priority-bg,#f8fbff);color:var(--text-color);text-decoration:none;transition:.18s}.priority-card:hover{transform:translateY(-1px);border-color:var(--priority-color,#2563eb);box-shadow:0 7px 17px color-mix(in srgb,var(--priority-color,#2563eb) 14%,transparent)}.priority-card>i{width:34px;height:34px;display:grid;place-items:center;border-radius:10px;background:color-mix(in srgb,var(--priority-color,#2563eb) 12%,white);color:var(--priority-color,#2563eb)}.priority-card span strong,.priority-card span small{display:block}.priority-card span strong{font-size:11px}.priority-card span small{margin-top:3px;color:var(--text-muted);font-size:9px}.priority-card>b{font-size:18px;color:var(--priority-color,#2563eb)}
.quick-list,.movement-list{display:grid;gap:8px}.quick-action{display:grid;grid-template-columns:34px 1fr auto;align-items:center;gap:10px;padding:9px 10px;border:1px solid var(--border-color);border-radius:11px;color:var(--text-color);text-decoration:none}.quick-action:hover{border-color:#93c5fd;background:#f8fbff}.quick-action>i:first-child{width:34px;height:34px;display:grid;place-items:center;border-radius:9px;background:#eff6ff;color:#2563eb}.quick-action strong,.quick-action small{display:block}.quick-action strong{font-size:11px}.quick-action small{margin-top:2px;color:var(--text-muted);font-size:9px}.quick-action>i:last-child{color:#94a3b8;font-size:10px}
.movement-row{display:grid;grid-template-columns:32px 1fr auto;align-items:center;gap:9px;padding-bottom:8px;border-bottom:1px solid rgba(148,163,184,.17)}.movement-row:last-child{border-bottom:0}.movement-icon{width:30px;height:30px;display:grid;place-items:center;border-radius:9px;background:#ecfdf5;color:#059669}.movement-icon.salida{background:#fff7ed;color:#ea580c}.movement-row strong,.movement-row small{display:block}.movement-row strong{overflow:hidden;font-size:10px;text-overflow:ellipsis;white-space:nowrap}.movement-row small{margin-top:2px;color:var(--text-muted);font-size:8.5px}.movement-amount{text-align:right}.movement-amount b,.movement-amount span{display:block}.movement-amount b{font-size:11px}.movement-amount span{font-size:8px;color:var(--text-muted)}
.analytics-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:16px}.analytics-card{padding:22px;border:1px solid rgba(148,163,184,.2);border-radius:18px;background:var(--panel-bg);box-shadow:0 12px 32px rgba(15,23,42,.055)}.analytics-card h3{margin:0 0 5px;font-size:15px}.analytics-card>p{margin:0 0 20px;color:var(--text-muted);font-size:11px}.progress-row{margin-bottom:17px}.progress-label{display:flex;justify-content:space-between;margin-bottom:7px;font-size:11px}.progress-track{height:11px;border-radius:999px;background:var(--secondary-bg);overflow:hidden}.progress-fill{height:100%;border-radius:inherit;background:linear-gradient(90deg,var(--start),var(--end))}.financial-value{margin:14px 0 20px;color:#d97706;font-size:clamp(27px,3vw,40px);font-weight:800;letter-spacing:-.04em}.financial-insights{display:grid;grid-template-columns:1fr 1fr;gap:9px}.financial-insights div{padding:12px;border-radius:12px;background:var(--secondary-bg)}.financial-insights span,.financial-insights strong{display:block}.financial-insights span{color:var(--text-muted);font-size:9px;text-transform:uppercase;font-weight:800}.financial-insights strong{margin-top:6px;font-size:14px}.report-card{background:linear-gradient(145deg,var(--panel-bg),color-mix(in srgb,#2563eb 4%,var(--panel-bg)))}.report-card a{display:flex;align-items:center;justify-content:space-between;gap:15px;margin-top:16px;padding:14px;border:1px solid #bfdbfe;border-radius:13px;background:#eff6ff;color:#1d4ed8;text-decoration:none;font-weight:800}.empty-note{padding:20px;text-align:center;color:var(--text-muted);font-size:11px}
@media(max-width:1150px){.dashboard-kpis{grid-template-columns:repeat(2,1fr)}.dashboard-grid,.analytics-grid{grid-template-columns:1fr 1fr}.dashboard-grid .dashboard-card:last-child,.analytics-grid .report-card{grid-column:1/-1}}@media(max-width:720px){.dashboard-hero{align-items:flex-start;flex-direction:column}.dashboard-kpis,.dashboard-grid,.analytics-grid{grid-template-columns:1fr}.dashboard-grid .dashboard-card:last-child,.analytics-grid .report-card{grid-column:auto}.priority-grid{grid-template-columns:1fr}.financial-insights{grid-template-columns:1fr}}
</style>

<header class="dashboard-hero animate-fade-in">
    <div><h1>Dashboard general</h1><p>Resumen ejecutivo del inventario y la operación de bodega. Período activo: <strong><?= htmlspecialchars($periodoActivo['nombre'] ?? 'Sin período activo') ?></strong> · IVA <strong><?= number_format((float)$tasaIva, 2) ?>%</strong>.</p></div>
    <div class="dashboard-actions"><a href="index.php?route=reportes" class="btn-primary"><i class="fa-solid fa-file-lines"></i> Centro de reportes</a><a href="index.php?route=inv_items_sistema" class="btn-outline"><i class="fa-solid fa-plus"></i> Registrar equipo</a></div>
</header>

<section class="stats-row dashboard-kpis animate-fade-in" aria-label="Indicadores principales">
    <div class="stat-card"><div class="stat-icon blue"><i class="fa-solid fa-layer-group"></i></div><div><div class="stat-value"><?= number_format($totalActivos) ?></div><div class="stat-label">Registros activos</div></div></div>
    <div class="stat-card"><div class="stat-icon blue"><i class="fa-solid fa-boxes-stacked"></i></div><div><div class="stat-value"><?= number_format($totalConsumo) ?></div><div class="stat-label">Bienes de consumo corriente</div></div></div>
    <div class="stat-card"><div class="stat-icon green"><i class="fa-solid fa-circle-check"></i></div><div><div class="stat-value"><?= number_format($totalFijo) ?></div><div class="stat-label">Bienes de activo fijo</div></div></div>
    <div class="stat-card"><div class="stat-icon orange"><i class="fa-solid fa-chart-line"></i></div><div><div class="stat-value"><?= htmlspecialchars(CommonHelper::formatearImporte($valorInventariado)) ?></div><div class="stat-label">Valor inventariado</div></div></div>
</section>

<section class="dashboard-grid animate-fade-in" aria-label="Centro operativo">
    <article class="dashboard-card"><div class="card-heading"><div><h3>Prioridades operativas</h3><p>Abra el reporte de inventario con el segmento aplicado.</p></div></div><div class="priority-grid">
        <a class="priority-card" href="index.php?route=reportes&amp;tab=inventario&amp;stock=sin_stock&amp;generar=1" style="--priority-color:#dc2626;--priority-border:#fecaca;--priority-bg:#fffafa"><i class="fa-solid fa-box-open"></i><span><strong>Sin existencia</strong><small>Consumo corriente agotado</small></span><b><?= number_format((int)($operativo['sin_stock'] ?? 0)) ?></b></a>
        <a class="priority-card" href="index.php?route=reportes&amp;tab=inventario&amp;stock=stock_bajo&amp;generar=1" style="--priority-color:#d97706;--priority-border:#fde68a;--priority-bg:#fffdf5"><i class="fa-solid fa-triangle-exclamation"></i><span><strong>Stock bajo</strong><small>Existencia igual o menor al mínimo</small></span><b><?= number_format((int)($operativo['stock_bajo'] ?? 0)) ?></b></a>
        <a class="priority-card" href="index.php?route=reportes&amp;tab=inventario&amp;estado=MANTENIMIENTO&amp;generar=1" style="--priority-color:#7c3aed;--priority-border:#ddd6fe;--priority-bg:#fbfaff"><i class="fa-solid fa-screwdriver-wrench"></i><span><strong>Mantenimiento</strong><small>Bienes fuera de operación</small></span><b><?= number_format((int)($operativo['mantenimiento'] ?? 0)) ?></b></a>
        <a class="priority-card" href="index.php?route=reportes&amp;tab=inventario&amp;stock=sin_responsable&amp;generar=1" style="--priority-color:#2563eb"><i class="fa-solid fa-user-slash"></i><span><strong>Sin responsable</strong><small>Activos fijos por asignar</small></span><b><?= number_format((int)($operativo['sin_responsable'] ?? 0)) ?></b></a>
    </div></article>
    <article class="dashboard-card"><div class="card-heading"><div><h3>Acciones frecuentes</h3><p>Accesos adaptados al uso del usuario.</p></div></div><div class="quick-list"><?php foreach (($accionesFrecuentes ?? []) as $accion): ?><a class="quick-action" href="<?= htmlspecialchars($accion['url']) ?>"><i class="fa-solid <?= htmlspecialchars($accion['icono']) ?>"></i><span><strong><?= htmlspecialchars($accion['titulo']) ?></strong><small><?= htmlspecialchars($accion['detalle']) ?></small></span><i class="fa-solid fa-chevron-right"></i></a><?php endforeach; ?></div></article>
    <article class="dashboard-card"><div class="card-heading"><div><h3>Movimientos recientes</h3><p>Últimas entradas y salidas registradas.</p></div></div><?php if (!$movimientos): ?><div class="empty-note"><i class="fa-solid fa-clock-rotate-left"></i><br>No hay movimientos recientes.</div><?php endif; ?><div class="movement-list"><?php foreach ($movimientos as $movimiento): $esSalida = strtoupper((string)($movimiento['tipo_movimiento'] ?? '')) === 'EGRESO' || (int)($movimiento['salida'] ?? 0) > 0; $cantidad = $esSalida ? (int)($movimiento['salida'] ?? 0) : (int)($movimiento['entrada'] ?? 0); ?><div class="movement-row"><span class="movement-icon <?= $esSalida ? 'salida' : '' ?>"><i class="fa-solid <?= $esSalida ? 'fa-arrow-up' : 'fa-arrow-down' ?>"></i></span><div><strong><?= htmlspecialchars($movimiento['item_nombre'] ?? 'Ítem') ?></strong><small><?= htmlspecialchars(($movimiento['item_codigo'] ?? '').' · '.($movimiento['documento_secuencial'] ?? 'Sin documento')) ?></small></div><div class="movement-amount"><b><?= $esSalida ? '-' : '+' ?><?= number_format($cantidad) ?></b><span><?= !empty($movimiento['fecha_movimiento']) ? date('d/m H:i', strtotime($movimiento['fecha_movimiento'])) : '' ?></span></div></div><?php endforeach; ?></div></article>
</section>

<section class="analytics-grid animate-fade-in" aria-label="Análisis general">
    <article class="analytics-card"><h3>Composición del inventario</h3><p>Participación de cada tipo de bien sobre el total.</p><div class="progress-row"><div class="progress-label"><strong>Consumo corriente</strong><span><?= number_format($porcentajeConsumo, 1) ?>%</span></div><div class="progress-track"><div class="progress-fill" style="--start:#38bdf8;--end:#2563eb;width:<?= number_format($porcentajeConsumo, 2, '.', '') ?>%"></div></div></div><div class="progress-row"><div class="progress-label"><strong>Activo fijo</strong><span><?= number_format($porcentajeFijo, 1) ?>%</span></div><div class="progress-track"><div class="progress-fill" style="--start:#34d399;--end:#059669;width:<?= number_format($porcentajeFijo, 2, '.', '') ?>%"></div></div></div></article>
    <article class="analytics-card"><h3>Lectura financiera</h3><p>Valor consolidado del inventario activo.</p><div class="financial-value"><?= htmlspecialchars(CommonHelper::formatearImporte($valorInventariado)) ?></div><div class="financial-insights"><div><span>Promedio por registro</span><strong><?= htmlspecialchars(CommonHelper::formatearImporte($valorPromedio)) ?></strong></div><div><span>Registros valorados</span><strong><?= number_format($totalActivos) ?></strong></div></div></article>
    <article class="analytics-card report-card"><h3>Reportes integrales</h3><p>Consulte todas las operaciones por fecha, ID, estado, proveedor, categoría o texto. Exporte el resultado a Excel/CSV o imprímalo.</p><a href="index.php?route=reportes"><span><i class="fa-solid fa-chart-column"></i> Abrir centro de reportes</span><i class="fa-solid fa-arrow-right"></i></a></article>
</section>
