<?php
$puedeDespachar = !empty($_permisoVista['edit']) || !empty($_permisoVista['full']);
$pasoActivo = 4;
?>
<link rel="stylesheet" href="public/css/inv_flujo_bodega.css?v=<?= (int)@filemtime(ROOT_PATH.'public/css/inv_flujo_bodega.css') ?>">
<div class="wf-page">
 <header class="wf-hero"><div class="wf-title"><span><i class="fa-solid fa-dolly"></i></span><div><h1>Egresos de bodega</h1><p>Entrega requisiciones disponibles y descuenta las existencias con trazabilidad.</p></div></div></header>
 <?php require __DIR__.'/_flujo_bodega.php'; ?>

 <section class="wf-card"><div class="wf-card-head"><div><h2>Requisiciones pendientes de despacho</h2><p>Solo se descuentan las cantidades confirmadas y disponibles.</p></div><span class="wf-status pending"><?= count($notasPendientes) ?> pendiente(s)</span></div><div class="wf-card-body"><?php if(!$notasPendientes): ?><div class="wf-empty"><i class="fa-solid fa-circle-check"></i>No existen requisiciones pendientes.</div><?php endif; ?><?php foreach($notasPendientes as $nota): ?><details class="wf-dispatch"><summary><span class="wf-code"><?= htmlspecialchars($nota['secuencial']) ?></span><div><strong><?= htmlspecialchars($nota['motivo']) ?></strong><small><?= htmlspecialchars($nota['solicitante'].' → '.$nota['centro_consumo']) ?></small></div><span class="wf-status pending"><?= htmlspecialchars($nota['estado']) ?></span></summary><div class="wf-dispatch-body"><form action="index.php?route=egresos&amp;action=despacharNota" method="post"><input type="hidden" name="nota_id" value="<?= (int)$nota['id_nota'] ?>"><div class="wf-form-grid"><label class="span-2"><span>Receptor responsable</span><select name="receptor_id" required <?= $puedeDespachar?'':'disabled' ?>><option value="">Seleccione…</option><?php foreach($personal as $persona): ?><option value="<?= (int)$persona['id'] ?>"><?= htmlspecialchars($persona['nombre']) ?></option><?php endforeach; ?></select></label><label class="span-2"><span>Observaciones de entrega</span><input name="observaciones" maxlength="2000" <?= $puedeDespachar?'':'disabled' ?>></label></div><div><?php foreach($nota['detalles'] as $detalle): $pendiente=max(0,(int)$detalle['cantidad_pendiente']); ?><div class="wf-product-row"><div><strong><?= htmlspecialchars($detalle['item_secuencial'].' · '.$detalle['item_nombre']) ?></strong><small>Solicitado <?= (int)$detalle['cantidad_solicitada'] ?> · entregado <?= (int)$detalle['cantidad_entregada'] ?></small></div><span>Existencia <strong><?= (int)$detalle['stock_actual'] ?></strong></span><span>Pendiente <strong><?= $pendiente ?></strong></span><label>Entregar <input type="number" name="cantidades[<?= (int)$detalle['id_detalle'] ?>]" min="0" max="<?= min($pendiente,(int)$detalle['stock_actual']) ?>" value="0" <?= $puedeDespachar?'':'disabled' ?>></label></div><?php endforeach; ?></div><?php if($puedeDespachar): ?><div class="wf-actions"><button class="btn-primary"><i class="fa-solid fa-box-open"></i> Confirmar egreso</button></div><?php endif; ?></form></div></details><?php endforeach; ?></div></section>

 <section class="wf-card"><div class="wf-card-head"><div><h2>Historial de egresos</h2><p>Salidas confirmadas con responsable, destino y nota de origen.</p></div><span class="wf-status"><?= count($egresos) ?> registro(s)</span></div><div class="wf-table-wrap"><table class="wf-table"><thead><tr><th>Egreso</th><th>Fecha</th><th>Requisición</th><th>Destino</th><th>Responsable</th><th>Motivo</th><th>Unidades</th></tr></thead><tbody><?php if(!$egresos): ?><tr><td colspan="7" class="wf-empty"><i class="fa-solid fa-dolly"></i>No existen egresos registrados.</td></tr><?php endif; ?><?php foreach($egresos as $egreso): ?><tr><td><strong class="wf-code"><?= htmlspecialchars($egreso['secuencial']) ?></strong></td><td><?= htmlspecialchars($egreso['fecha']) ?></td><td><?= htmlspecialchars($egreso['nota_pedido_secuencial']??'—') ?></td><td><?= htmlspecialchars($egreso['area_destino']??'—') ?></td><td><?= htmlspecialchars($egreso['responsable']) ?></td><td><?= htmlspecialchars($egreso['motivo']) ?></td><td><?= (int)($egreso['total_items']??0) ?></td></tr><?php endforeach; ?></tbody></table></div></section>
</div>
