<?php
$pasoActivo = 2;
$editando = !empty($orden);
$detallesOrden = $orden['detalles'] ?? [];
$requisicionesJson = [];
foreach($requisicionesCompra as $requisicion) $requisicionesJson[(int)$requisicion['id_nota']]=$requisicion;
?>
<link rel="stylesheet" href="public/css/inv_flujo_bodega.css?v=<?= (int)@filemtime(ROOT_PATH.'public/css/inv_flujo_bodega.css') ?>">
<link rel="stylesheet" href="public/css/inv_flujo_bodega_moderno.css?v=<?= (int)@filemtime(ROOT_PATH.'public/css/inv_flujo_bodega_moderno.css') ?>">
<link rel="stylesheet" href="public/css/inv_ordenes_compra.css?v=<?= (int)@filemtime(ROOT_PATH.'public/css/inv_ordenes_compra.css') ?>">
<div class="wf-page oc-create-page">
    <header class="wf-hero"><div class="wf-title"><span><i class="fa-solid fa-cart-plus"></i></span><div><h1><?= $editando?'Editar '.htmlspecialchars($orden['secuencial']):'Nueva orden de compra' ?></h1><p>Cabecera y movimiento de productos en una página completa.</p></div></div><span class="wf-period <?= $periodoActivo?'active':'inactive' ?>"><i class="fa-solid <?= $periodoActivo?'fa-circle-check':'fa-triangle-exclamation' ?>"></i><?= $periodoActivo?'Período '.htmlspecialchars($periodoActivo['nombre']).' activo':'Sin período activo' ?></span></header>
    <?php require __DIR__.'/_flujo_bodega.php'; ?>
    <nav class="oc-tabs"><a href="index.php?route=ordenes_compra"><i class="fa-solid fa-list"></i> Lista de órdenes</a><a class="active" href="index.php?route=ordenes_compra&amp;action=nuevaOrdenCompra"><i class="fa-solid fa-file-circle-plus"></i> <?= $editando?'Editar orden':'Nueva orden' ?></a></nav>
    <?php if(!$esquemaDisponible||!$periodoActivo): ?><section class="wf-card oc-blocked"><i class="fa-solid fa-triangle-exclamation"></i><h2>No se puede procesar la orden</h2><p><?= !$esquemaDisponible?'El esquema de abastecimiento no está disponible.':'No existe un período activo. Abra un período antes de crear o editar una orden de compra.' ?></p><a class="btn-outline" href="index.php?route=ordenes_compra">Volver a la lista</a></section><?php else: ?>
    <form class="wf-card oc-form-card" id="oc-form" action="index.php?route=ordenes_compra&amp;action=<?= $editando?'editarOrdenCompra':'guardarOrdenCompra' ?>" method="post"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>"><?php if($editando): ?><input type="hidden" name="orden_id" value="<?= (int)$orden['id_orden'] ?>"><?php endif; ?>
        <section class="oc-head"><div class="oc-head-fields"><label><span>N.º orden</span><input value="<?= $editando?htmlspecialchars($orden['secuencial']):'AUTOMÁTICO' ?>" readonly></label><label><span>Fecha</span><input type="date" name="fecha" value="<?= htmlspecialchars($orden['fecha']??date('Y-m-d')) ?>" required></label><label class="oc-provider-field"><span>Proveedor</span><div class="oc-provider-control"><select name="proveedor_id" id="oc-provider" data-searchable-select data-search-placeholder="Buscar proveedor por código, nombre o RUC…" required><option value="">Escriba para buscar…</option><?php foreach($proveedores as $proveedor): ?><option value="<?= (int)$proveedor['id'] ?>" <?= (int)($orden['proveedor_id']??0)===(int)$proveedor['id']?'selected':'' ?>><?= htmlspecialchars(($proveedor['codigo']? $proveedor['codigo'].' · ':'').$proveedor['nombre'].($proveedor['ruc']?' · '.$proveedor['ruc']:'')) ?></option><?php endforeach; ?></select><button class="oc-add-provider" id="oc-show-provider" type="button" title="Crear proveedor"><i class="fa-solid fa-plus"></i></button></div></label><label class="oc-detail-field"><span>Detalle</span><input name="observaciones" maxlength="2000" value="<?= htmlspecialchars($orden['observaciones']??'') ?>" placeholder="Detalle u observaciones de la compra"></label></div></section>
        <section class="oc-quick-provider" id="oc-quick-provider" hidden><div class="oc-quick-head"><div><strong>Crear proveedor</strong><small>Se agregará y seleccionará sin perder la orden.</small></div><button type="button" id="oc-hide-provider"><i class="fa-solid fa-xmark"></i></button></div><div class="oc-quick-grid"><label>Razón social<input name="quick_nombre" maxlength="255"></label><label>RUC<input name="quick_ruc" maxlength="13" inputmode="numeric"></label><label>Representante<input name="quick_representante" maxlength="255"></label><label>Teléfono<input name="quick_telefono1" maxlength="50"></label><label>Correo<input name="quick_email" type="email" maxlength="180"></label><label>Ciudad<input name="quick_ciudad" maxlength="150"></label><label class="full">Dirección<input name="quick_direccion" maxlength="500"></label></div><div class="oc-quick-actions"><span id="oc-provider-status"></span><button class="btn-primary" id="oc-save-provider" type="button"><i class="fa-solid fa-building-circle-check"></i> Guardar proveedor</button></div></section>
        <section class="oc-document-fields"><label><span>Requisición de origen <small>Opcional</small></span><select name="requisicion_id" id="oc-requisition" data-searchable-select data-search-placeholder="Buscar requisición…"><option value="">Orden directa, sin requisición</option><?php foreach($requisicionesCompra as $requisicion): ?><option value="<?= (int)$requisicion['id_nota'] ?>" <?= (int)($orden['requisicion_id']??0)===(int)$requisicion['id_nota']?'selected':'' ?>><?= htmlspecialchars($requisicion['secuencial'].' · '.$requisicion['centro_consumo'].' · '.$requisicion['motivo']) ?></option><?php endforeach; ?></select></label><label><span>Dirección requirente</span><input name="direccion_requirente" maxlength="255" value="<?= htmlspecialchars($orden['direccion_requirente']??'') ?>"></label><label><span>Memorando de solicitud</span><input name="memorando_solicitud" maxlength="100" value="<?= htmlspecialchars($orden['memorando_solicitud']??'') ?>"></label><label><span>Requerimiento autorizado por</span><input name="autorizado_por" maxlength="255" value="<?= htmlspecialchars($orden['autorizado_por']??'') ?>"></label><label><span>Acta de selección de proveedor</span><input name="acta_seleccion" maxlength="100" value="<?= htmlspecialchars($orden['acta_seleccion']??'') ?>"></label><label><span>Certificación presupuestaria</span><input name="certificacion_presupuestaria" maxlength="100" value="<?= htmlspecialchars($orden['certificacion_presupuestaria']??'') ?>"></label><label><span>Plazo de entrega</span><input name="plazo_entrega" maxlength="100" value="<?= htmlspecialchars($orden['plazo_entrega']??'') ?>"></label><label><span>Forma de pago</span><input name="forma_pago" maxlength="100" value="<?= htmlspecialchars($orden['forma_pago']??'') ?>"></label><label><span>Condiciones para el pago</span><input name="condiciones_pago" maxlength="255" value="<?= htmlspecialchars($orden['condiciones_pago']??'') ?>"></label></section>
        <section class="oc-grid-section"><div class="oc-grid-head"><div><h2>Movimiento de la orden de compra</h2><p>Agregue o busque los productos directamente en la grilla.</p></div><button class="btn-outline" id="oc-add-line" type="button"><i class="fa-solid fa-plus"></i> Agregar fila</button></div><div class="oc-grid-wrap"><table class="oc-grid"><thead><tr><th>#</th><th>Pedido</th><th>Requisición</th><th>Ítem</th><th>Descripción</th><th>Referencia</th><th>Cantidad</th><th>P. unitario</th><th>Subtotal</th><th>IVA</th><th>Total</th><th>Especificaciones técnicas</th><th></th></tr></thead><tbody id="oc-lines"></tbody></table></div><div class="oc-totals"><div><span>Subtotal</span><strong id="oc-subtotal">$0.00</strong></div><div><span>Base 0%</span><strong id="oc-base0">$0.00</strong></div><div><span>Base gravada</span><strong id="oc-tax-base">$0.00</strong></div><div><span>IVA</span><strong id="oc-tax">$0.00</strong></div><div class="final"><span>Total</span><strong id="oc-total">$0.00</strong></div></div></section>
        <footer class="oc-form-footer"><a class="btn-outline" href="index.php?route=ordenes_compra"><i class="fa-solid fa-arrow-left"></i> Volver</a><button class="btn-primary"><i class="fa-solid fa-floppy-disk"></i> <?= $editando?'Guardar cambios':'Guardar orden' ?></button></footer>
    </form><?php endif; ?>
</div>
<?php if($esquemaDisponible&&$periodoActivo): ?><template id="oc-line-template"><tr><td class="oc-row-number"></td><td><input class="oc-order-note" maxlength="100"></td><td><input class="oc-requisition-number" maxlength="100"></td><td class="oc-item-code">—</td><td class="oc-product-cell"><div><i class="fa-solid fa-magnifying-glass"></i><input class="oc-product-search" placeholder="Código, nombre, marca, categoría o unidad…" autocomplete="off"><input class="oc-item-id" type="hidden" required></div></td><td><input class="oc-reference" maxlength="255"></td><td><input class="oc-quantity" type="number" min="1" step="1" value="1" required></td><td><input class="oc-price" data-price-input type="number" min="0" step="<?= htmlspecialchars(CommonHelper::pasoPrecio()) ?>" value="0" required></td><td class="oc-line-subtotal"><?= htmlspecialchars(CommonHelper::formatearImporte(0)) ?></td><td><select class="oc-grava"><option value="1">Aplica</option><option value="0">0%</option></select><input class="oc-rate" type="hidden" value="<?= htmlspecialchars((string)$ivaPredeterminado) ?>"><small class="oc-line-tax"><?= htmlspecialchars(CommonHelper::formatearImporte(0)) ?></small></td><td class="oc-line-total"><?= htmlspecialchars(CommonHelper::formatearImporte(0)) ?></td><td><input class="oc-specifications" maxlength="1000"></td><td><button class="oc-remove" type="button"><i class="fa-solid fa-trash"></i></button></td></tr></template><div class="oc-product-results" id="oc-product-results"></div><script>window.ocOrderConfig=<?= json_encode(['iva'=>(float)$ivaPredeterminado,'requisiciones'=>$requisicionesJson,'detalles'=>$detallesOrden,'csrf'=>$csrfToken],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>;</script><script src="public/js/inv_ordenes_compra.js?v=<?= (int)@filemtime(ROOT_PATH.'public/js/inv_ordenes_compra.js') ?>"></script><?php endif; ?>
