<?php
$estado = (string)($nota['estado'] ?? '');
$estadoVisible = $estado === 'CANCELADA' ? 'ANULADA' : (in_array($estado, ['ENVIADA','EN_REVISION','DISPONIBLE','PARCIAL','SIN_EXISTENCIAS'], true) ? 'PENDIENTE' : $estado);
?>
<style>
.rq-print{max-width:980px;margin:0 auto;padding:24px;color:#172033;background:#fff}.rq-print-head{display:flex;justify-content:space-between;gap:24px;padding-bottom:18px;border-bottom:2px solid #245b9e}.rq-print h1{margin:0 0 6px;font-size:25px;color:#173f73}.rq-print p{margin:3px 0;color:#526274}.rq-print-meta{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:20px 0}.rq-print-meta div{padding:12px;border:1px solid #d8e0ea;border-radius:8px}.rq-print-meta span,.rq-print-meta strong{display:block}.rq-print-meta span{font-size:10px;text-transform:uppercase;color:#68778a}.rq-print-meta strong{margin-top:4px}.rq-print table{width:100%;border-collapse:collapse}.rq-print th,.rq-print td{padding:10px;border:1px solid #d7dfe9;text-align:left}.rq-print th{background:#edf4fb;color:#173f73;font-size:11px;text-transform:uppercase}.rq-print-actions{display:flex;justify-content:flex-end;gap:10px;margin-bottom:18px}.rq-print-notes{margin-top:18px;padding:14px;border:1px solid #d8e0ea;border-radius:8px}.rq-print-signatures{display:grid;grid-template-columns:1fr 1fr;gap:80px;margin-top:70px}.rq-print-signatures div{padding-top:8px;border-top:1px solid #374151;text-align:center}@media print{.sidebar,.top-header,.rq-print-actions{display:none!important}.main-content,.content{margin:0!important;padding:0!important}.rq-print{max-width:none;padding:0}@page{size:A4;margin:14mm}}
</style>
<article class="rq-print">
 <div class="rq-print-actions"><a class="btn-outline" href="index.php?route=requisiciones"><i class="fa-solid fa-arrow-left"></i> Volver</a><button class="btn-primary" type="button" onclick="window.print()"><i class="fa-solid fa-print"></i> Imprimir</button></div>
 <header class="rq-print-head"><div><h1>Requisición de productos</h1><p>Sistema de Bodega</p></div><div><strong><?= htmlspecialchars($nota['secuencial']) ?></strong><p><?= htmlspecialchars($estadoVisible) ?></p></div></header>
 <section class="rq-print-meta"><div><span>Fecha</span><strong><?= htmlspecialchars($nota['fecha_solicitud']) ?></strong></div><div><span>Centro de consumo</span><strong><?= htmlspecialchars($nota['centro_consumo']) ?></strong></div><div><span>Responsable</span><strong><?= htmlspecialchars($nota['receptor'] ?? '—') ?></strong></div><div><span>Tipo</span><strong><?= htmlspecialchars(($nota['tipo_bien']??'CC') === 'AF' ? 'Activo fijo' : 'Consumo corriente') ?></strong></div></section>
 <section><h2>Detalle de productos</h2><table><thead><tr><th>#</th><th>Código</th><th>Descripción</th><th>Solicitado</th><th>Entregado</th><th>Pendiente</th><th>Existencia</th></tr></thead><tbody><?php foreach(($nota['detalles']??[]) as $indice=>$detalle): ?><tr><td><?= $indice+1 ?></td><td><strong><?= htmlspecialchars($detalle['item_codigo']??$detalle['item_secuencial']??'—') ?></strong></td><td><?= htmlspecialchars($detalle['item_nombre']??'') ?></td><td><?= (int)$detalle['cantidad_solicitada'] ?></td><td><?= (int)$detalle['cantidad_entregada'] ?></td><td><?= (int)$detalle['cantidad_pendiente'] ?></td><td><?= (int)$detalle['stock_actual'] ?></td></tr><?php endforeach; ?></tbody></table></section>
 <section class="rq-print-notes"><strong>Finalidad</strong><p><?= nl2br(htmlspecialchars($nota['motivo']??'')) ?></p><?php if(trim((string)($nota['observaciones']??''))!==''): ?><strong>Observaciones</strong><p><?= nl2br(htmlspecialchars($nota['observaciones'])) ?></p><?php endif; ?></section>
 <footer class="rq-print-signatures"><div>Responsable del centro</div><div>Responsable de Bodega</div></footer>
</article>
