<?php
$puedeCrear = !empty($_permisoVista['create']) || !empty($_permisoVista['full']);
$pasoActivo = 1;
?>
<link rel="stylesheet" href="public/css/inv_flujo_bodega.css?v=<?= (int)@filemtime(ROOT_PATH.'public/css/inv_flujo_bodega.css') ?>">
<div class="wf-page">
 <header class="wf-hero"><div class="wf-title"><span><i class="fa-solid fa-clipboard-list"></i></span><div><h1>Requisiciones</h1><p>Solicitudes internas que dan inicio al flujo de abastecimiento y despacho.</p></div></div></header>
 <?php require __DIR__.'/_flujo_bodega.php'; ?>

 <?php if($puedeCrear): ?><section class="wf-card" id="wf-requisition-form"><div class="wf-card-head"><div><h2>Nueva requisición</h2><p>Indique quién solicita, para quién se requiere y los productos necesarios.</p></div><i class="fa-solid fa-file-circle-plus"></i></div><form class="wf-card-body" action="index.php?route=requisiciones&amp;action=guardarSolicitud" method="post" id="wf-request-form"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(csrf_token()) ?>"><div class="wf-form-grid"><label><span>Fecha</span><input type="date" name="fecha_solicitud" value="<?= date('Y-m-d') ?>" required></label><label><span>Solicitante</span><select name="solicitante_id" required><option value="">Seleccione…</option><?php foreach($personal as $persona): ?><option value="<?= (int)$persona['id'] ?>"><?= htmlspecialchars($persona['nombre']) ?></option><?php endforeach; ?></select></label><label class="span-2"><span>Centro de consumo / persona destinataria</span><select name="centro_consumo_persona_id" required><option value="">Seleccione…</option><?php foreach($personal as $persona): ?><option value="<?= (int)$persona['id'] ?>"><?= htmlspecialchars($persona['nombre'].(!empty($persona['area'])?' · '.$persona['area']:'')) ?></option><?php endforeach; ?></select></label><label class="span-2"><span>Motivo</span><input name="motivo" maxlength="500" placeholder="Finalidad de la requisición" required></label><label class="span-2"><span>Observaciones</span><input name="observaciones" maxlength="2000" placeholder="Información adicional opcional"></label></div><div class="wf-lines" id="wf-request-lines"></div><div class="wf-actions"><button class="btn-outline" type="button" id="wf-add-request-line"><i class="fa-solid fa-plus"></i> Agregar producto</button><button class="btn-primary"><i class="fa-solid fa-paper-plane"></i> Registrar requisición</button></div></form></section><?php endif; ?>

 <section class="wf-card"><div class="wf-card-head"><div><h2>Requisiciones registradas</h2><p>Cada solicitud conserva cantidades solicitadas, entregadas y pendientes.</p></div><span class="wf-status"><?= count($notas) ?> registro(s)</span></div><div class="wf-table-wrap"><table class="wf-table"><thead><tr><th>Requisición</th><th>Fecha</th><th>Solicitante</th><th>Destino</th><th>Motivo</th><th>Productos</th><th>Solicitado</th><th>Entregado</th><th>Estado</th></tr></thead><tbody><?php if(!$notas): ?><tr><td colspan="9" class="wf-empty"><i class="fa-solid fa-clipboard"></i>No existen requisiciones registradas.</td></tr><?php endif; ?><?php foreach($notas as $nota): $final=in_array($nota['estado'],['ATENDIDA','CERRADA'],true); ?><tr><td><strong class="wf-code"><?= htmlspecialchars($nota['secuencial']) ?></strong></td><td><?= htmlspecialchars($nota['fecha_solicitud']) ?></td><td><?= htmlspecialchars($nota['solicitante']) ?></td><td><?= htmlspecialchars($nota['centro_consumo']) ?></td><td><?= htmlspecialchars($nota['motivo']) ?></td><td><?= (int)$nota['total_productos'] ?></td><td><?= (int)$nota['total_solicitado'] ?></td><td><?= (int)$nota['total_entregado'] ?></td><td><span class="wf-status <?= $final?'done':'pending' ?>"><?= htmlspecialchars($nota['estado']) ?></span></td></tr><?php endforeach; ?></tbody></table></div></section>
</div>
<template id="wf-request-line-template"><div class="wf-line"><label><span>Producto</span><select class="wf-item" required><option value="">Seleccione un producto…</option><?php foreach($itemsInventario as $item): ?><option value="<?= (int)$item['id'] ?>"><?= htmlspecialchars($item['secuencial'].' · '.$item['nombre'].' · existencia '.(int)($item['cantidad']??0)) ?></option><?php endforeach; ?></select></label><label><span>Cantidad</span><input class="wf-quantity" type="number" min="1" step="1" value="1" required></label><button class="wf-remove" type="button" title="Quitar"><i class="fa-solid fa-trash"></i></button></div></template>
<script>
(()=>{const host=document.getElementById('wf-request-lines'),tpl=document.getElementById('wf-request-line-template'),add=document.getElementById('wf-add-request-line');if(!host||!tpl||!add)return;function names(){[...host.children].forEach((row,i)=>{row.querySelector('.wf-item').name=`items[${i}][item_id]`;row.querySelector('.wf-quantity').name=`items[${i}][cantidad]`})}function line(){const row=tpl.content.firstElementChild.cloneNode(true);row.querySelector('.wf-remove').onclick=()=>{row.remove();names()};host.appendChild(row);names()}add.onclick=line;line()})();
</script>
